document:
  name: pagoPA, Guida Tecnica Avviso Analogico
  description: |
    Guida Tecnica Avviso Analogico di pagoPA versione 2.1
    Lo scopo del documento è quello di fornire indicazioni per la produzione
    dell’avviso analogico di pagamento pagoPA.
    Il documento è di riferimento per gli Enti Creditori ed i Prestatori di
    Servizi di Pagamento.
  tags:
    - SANP
    - pagoPA
    - SACI
    - AgID
